In [1]:
from ascfd.inputs import Inputs
from ascfd.simulation import Simulation

inp = Inputs("problems/hall_thruster.ini")
s = Simulation(inp)

/Users/matthewfang/anaconda3/lib/python3.10/site-packages/pandas/core/arrays/masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


CALLED PHYS TO NORMAL
normal_inp.dx 0.0005
normal_inp.xlim (0.0, 0.05)
INITIALIZED ELECTRONS
[ics] QN STATIC!!
[ics] INIT WITH: [[1.e+17 1.e+17 1.e+17 ... 1.e+17 1.e+17 1.e+17]
 [1.e+17 1.e+17 1.e+17 ... 1.e+17 1.e+17 1.e+17]
 [1.e+17 1.e+17 1.e+17 ... 1.e+17 1.e+17 1.e+17]
 ...
 [1.e+17 1.e+17 1.e+17 ... 1.e+17 1.e+17 1.e+17]
 [1.e+17 1.e+17 1.e+17 ... 1.e+17 1.e+17 1.e+17]
 [1.e+17 1.e+17 1.e+17 ... 1.e+17 1.e+17 1.e+17]]
Loaded elastic: 199 data points from 0.000e+00 to 9.651e+02 eV
Loaded exc1: 201 data points from 8.315e+00 to 9.734e+02 eV
Loaded exc2: 201 data points from 9.447e+00 to 9.745e+02 eV
Loaded exc3: 201 data points from 9.917e+00 to 9.750e+02 eV
Loaded exc4: 201 data points from 1.170e+01 to 9.768e+02 eV
Loaded ionization: 201 data points from 1.213e+01 to 9.772e+02 eV
Loaded ion_elastic: 114 data points from 0.000e+00 to 1.000e+04 eV
Loaded ion_backward: 114 data points from 0.000e+00 to 1.000e+04 eV
Initialized i with 5 components, capacity 137280
Initialized 45760 a

In [2]:
s.run()

Timestep: 0, Current time: 0.0
!START! BEGINNING UPDATE: first active particles = [0. 0. 0.]
!B! BEFORE BOUNDARY CHECK: x_positions = []
!B! AFTER BOUNDARY CHECK: x_positions = []
--##-- COLLISION EVENTS FOR n
ionization 0.0
excitations 0.0
elastic 0.0
!END! END UPDATE: first active particles = NONE
!START! BEGINNING UPDATE: first active particles = [0. 0. 0.]
!B! BEFORE BOUNDARY CHECK: x_positions = []
!B! AFTER BOUNDARY CHECK: x_positions = []
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k
got all k


/Users/matthewfang/Documents/GitHub/realASCFD/ascfd/fluid/quasineutral/species.py:155: LinAlgWarning: Ill-conditioned matrix (rcond=5.79857e-42): result may not be accurate.
  _energy_e_plus = linalg.solve(a, b, assume_a='tridiagonal')


X LIM 0.05
y LIM 0.05
Timestep: 1, Current time: 1e-10
!START! BEGINNING UPDATE: first active particles = NONE
--##-- COLLISION EVENTS FOR n
ionization 0.0
excitations 0.0
elastic 0.0
!END! END UPDATE: first active particles = NONE
!START! BEGINNING UPDATE: first active particles = NONE


IndexError: single positional indexer is out-of-bounds