In [1]:
from ascfd.inputs import Inputs
from ascfd.simulation import Simulation

In [2]:
inp = Inputs("problems/mhd_test.ini")


In [3]:
s = Simulation(inp)


ValueError: Unexpected variable: 4

In [4]:
s.run()

Timestep: 0, Current time: 0.0
actual: [[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0.

/Users/matthewfang/Documents/GitHub/realASCFD/ascfd/simulation.py:46: RuntimeWarning: invalid value encountered in divide
  a = np.sqrt(self.c.gamma * self.grid.grid[self.c.PCOMP] / density)
/Users/matthewfang/Documents/GitHub/realASCFD/ascfd/flux.py:241: RuntimeWarning: invalid value encountered in divide
  a = np.sqrt(self.c.gamma * a_grid.grid[self.c.PCOMP] / density)
/Users/matthewfang/Documents/GitHub/realASCFD/ascfd/euler.py:28: RuntimeWarning: invalid value encountered in divide
  E = (a_prim[self.c.PCOMP] / ((self.c.gamma - 1) * a_prim[self.c.RHOCOMP]) +
/Users/matthewfang/Documents/GitHub/realASCFD/ascfd/flux.py:141: RuntimeWarning: invalid value encountered in divide
  a = np.sqrt(self.c.gamma * a_grid.grid[self.c.PCOMP] / density)
/Users/matthewfang/Documents/GitHub/realASCFD/ascfd/flux.py:175: RuntimeWarning: invalid value encountered in double_scalars
  cf_L = np.sqrt((pT_L + Bx**2) / rho_L)
/Users/matthewfang/Documents/GitHub/realASCFD/ascfd/flux.py:176: RuntimeWarning: i

ValueError: 